% Using fitbogartz function from https://www.mathworks.com/matlabcentral/fileexchange/124190-piecewise-linear-model
% Download from the link and extract all files to same directory as this file

% IMPORTANT
% This code will only work if all files are in the same directory
% If not cd() functions have to be added

analysisfile = readmatrix('20230113_analysis.csv'); % Change to name of csv file 
timestamp = readtable('20230113_display.csv', 'NumHeaderLines',1); % Timestamps obtained from csv file generated by MATLAB Data Explorer
coefficients = fitBogartz(analysisfile(:,11), analysisfile(:,8), 1);

scatter(analysisfile(:,11), analysisfile(:,8), 'r', '.');
refline(coefficients(1),coefficients(2));
refline(coefficients(3),coefficients(4));

title('Sensor Voltage Against Solar Irradiance');
xlabel('Solar Irradiance (W/m^2)');
ylabel('Sensor Voltage (V)');
